// Original file: proto/model_config.proto

/**
 * @@
 * @@ .. cpp:var:: message ModelTransactionPolicy
 * @@
 * @@    The specification that describes the nature of transactions
 * @@    to be expected from the model.
 * @@
 */
export interface ModelTransactionPolicy {
  /**
   * @@  .. cpp:var:: bool decoupled
   * @@
   * @@     Indicates whether responses generated by the model are decoupled with
   * @@     the requests issued to it, which means the number of responses
   * @@     generated by model may differ from number of requests issued, and
   * @@     that the responses may be out of order relative to the order of
   * @@     requests. The default is false, which means the model will generate
   * @@     exactly one response for each request.
   * @@
   */
  decoupled?: boolean;
}

/**
 * @@
 * @@ .. cpp:var:: message ModelTransactionPolicy
 * @@
 * @@    The specification that describes the nature of transactions
 * @@    to be expected from the model.
 * @@
 */
export interface ModelTransactionPolicy__Output {
  /**
   * @@  .. cpp:var:: bool decoupled
   * @@
   * @@     Indicates whether responses generated by the model are decoupled with
   * @@     the requests issued to it, which means the number of responses
   * @@     generated by model may differ from number of requests issued, and
   * @@     that the responses may be out of order relative to the order of
   * @@     requests. The default is false, which means the model will generate
   * @@     exactly one response for each request.
   * @@
   */
  decoupled: boolean;
}
